/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariffRatezone {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ratezone_status_id", skip_serializing_if = "Option::is_none")]
    pub ratezone_status_id: Option<i32>,
}

impl ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariffRatezone {
    pub fn new() -> ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariffRatezone {
        ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariffRatezone {
            id: None,
            name: None,
            ratezone_status_id: None,
        }
    }
}


