/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariff {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "tariff_status_id", skip_serializing_if = "Option::is_none")]
    pub tariff_status_id: Option<i32>,
    #[serde(rename = "ratezone", skip_serializing_if = "Option::is_none")]
    pub ratezone: Option<crate::models::ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariffRatezone>,
}

impl ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariff {
    pub fn new() -> ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariff {
        ApiV1OrganisationOrgIdOrMyInclusiveVolumeActiveTariff {
            id: None,
            name: None,
            tariff_status_id: None,
            ratezone: None,
        }
    }
}


