/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1UserMfaKeyIdStatus {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<f32>,
}

impl ApiV1UserMfaKeyIdStatus {
    pub fn new() -> ApiV1UserMfaKeyIdStatus {
        ApiV1UserMfaKeyIdStatus {
            id: None,
            code: None,
        }
    }
}


