/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountActivationrequest {
    #[serde(rename = "activationKey")]
    pub activation_key: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl AccountActivationrequest {
    pub fn new(activation_key: String, password: String) -> AccountActivationrequest {
        AccountActivationrequest {
            activation_key,
            password,
        }
    }
}
