/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActivateMfaKeyRequest {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::ActivateMfaKeyRequestStatus>>,
}

impl ActivateMfaKeyRequest {
    pub fn new() -> ActivateMfaKeyRequest {
        ActivateMfaKeyRequest { status: None }
    }
}
