/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOnExhaustion {
    #[serde(rename = "id")]
    pub id: Id,
    // #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    // pub description: Option<crate::models::OneOfString>,
    #[serde(rename = "peak_throughput")]
    pub peak_throughput: f32,
}

impl ActionOnExhaustion {
    pub fn new(id: Id, peak_throughput: f32) -> ActionOnExhaustion {
        ActionOnExhaustion {
            id,
            // description: None,
            peak_throughput,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Id {
    #[serde(rename = "1")]
    _1,
    #[serde(rename = "2")]
    _2,
}

