/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActionOnExhaustion {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Description>,
    #[serde(rename = "peak_throughput", skip_serializing_if = "Option::is_none")]
    pub peak_throughput: Option<i32>,
}

impl ActionOnExhaustion {
    pub fn new(id: Id) -> ActionOnExhaustion {
        ActionOnExhaustion {
            id,
            description: None,
            peak_throughput: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Id {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
}

impl Default for Id {
    fn default() -> Id {
        Self::Variant1
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Description {
    #[serde(rename = "Throttle")]
    Throttle,
    #[serde(rename = "Block")]
    Block,
}

impl Default for Description {
    fn default() -> Description {
        Self::Throttle
    }
}
