/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateUserrequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "organisation")]
    pub organisation: serde_json::Value,
    ///
    #[serde(rename = "roles")]
    pub roles: Vec<serde_json::Value>,
}

impl CreateUserrequest {
    pub fn new(
        username: String,
        name: String,
        organisation: serde_json::Value,
        roles: Vec<serde_json::Value>,
    ) -> CreateUserrequest {
        CreateUserrequest {
            username,
            name,
            organisation,
            roles,
        }
    }
}
