/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateApplicationTokenresponse {
    #[serde(rename = "application_token", skip_serializing_if = "Option::is_none")]
    pub application_token: Option<String>,
}

impl CreateApplicationTokenresponse {
    pub fn new() -> CreateApplicationTokenresponse {
        CreateApplicationTokenresponse {
            application_token: None,
        }
    }
}
