/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateaDnSentryrequest {
    #[serde(rename = "primary")]
    pub primary: String,
    #[serde(rename = "secondary")]
    pub secondary: String,
    #[serde(rename = "ip_address_version")]
    pub ip_address_version: i32,
}

impl CreateaDnSentryrequest {
    pub fn new(
        primary: String,
        secondary: String,
        ip_address_version: i32,
    ) -> CreateaDnSentryrequest {
        CreateaDnSentryrequest {
            primary,
            secondary,
            ip_address_version,
        }
    }
}
