/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDataStreamer422Response {
    #[serde(rename = "error_code")]
    pub error_code: i32,
    #[serde(rename = "error_token")]
    pub error_token: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl CreateDataStreamer422Response {
    pub fn new(
        error_code: i32,
        error_token: String,
        message: String,
    ) -> CreateDataStreamer422Response {
        CreateDataStreamer422Response {
            error_code,
            error_token,
            message,
        }
    }
}
