/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataQuota {
    #[serde(rename = "last_volume_added", skip_serializing_if = "Option::is_none")]
    pub last_volume_added: Option<f32>,
    #[serde(rename = "last_status_change_date", skip_serializing_if = "Option::is_none")]
    pub last_status_change_date: Option<String>,
    #[serde(rename = "auto_refill", skip_serializing_if = "Option::is_none")]
    pub auto_refill: Option<f32>,
    #[serde(rename = "threshold_percentage")]
    pub threshold_percentage: f32,
    #[serde(rename = "status")]
    pub status: crate::models::QuotaStatus,
    #[serde(rename = "volume")]
    pub volume: f32,
    #[serde(rename = "expiry_date")]
    pub expiry_date: String,
    #[serde(rename = "action_on_exhaustion")]
    pub action_on_exhaustion: crate::models::ActionOnExhaustion,
}

impl DataQuota {
    pub fn new(threshold_percentage: f32, status: crate::models::QuotaStatus, volume: f32, expiry_date: String, action_on_exhaustion: crate::models::ActionOnExhaustion) -> DataQuota {
        DataQuota {
            last_volume_added: None,
            last_status_change_date: None,
            auto_refill: None,
            threshold_percentage,
            status,
            volume,
            expiry_date,
            action_on_exhaustion,
        }
    }
}


