/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Endpoint {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::Status>,
    #[serde(rename = "service_profile")]
    pub service_profile: Box<crate::models::ServiceProfile>,
    #[serde(rename = "tariff_profile")]
    pub tariff_profile: Box<crate::models::TariffProfile>,
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "ip_address_space", skip_serializing_if = "Option::is_none")]
    pub ip_address_space: Option<Box<crate::models::HasId>>,
    #[serde(rename = "sim", skip_serializing_if = "Option::is_none")]
    pub sim: Option<Box<crate::models::Sim>>,
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(rename = "imei_lock", skip_serializing_if = "Option::is_none")]
    pub imei_lock: Option<bool>,
    #[serde(rename = "runtime_data", skip_serializing_if = "Option::is_none")]
    pub runtime_data: Option<Box<crate::models::EndpointRuntimeData>>,
}

impl Endpoint {
    pub fn new(
        name: String,
        status: crate::models::Status,
        service_profile: crate::models::ServiceProfile,
        tariff_profile: crate::models::TariffProfile,
    ) -> Endpoint {
        Endpoint {
            id: None,
            name,
            tags: None,
            created: None,
            last_updated: None,
            status: Box::new(status),
            service_profile: Box::new(service_profile),
            tariff_profile: Box::new(tariff_profile),
            ip_address: None,
            ip_address_space: None,
            sim: None,
            imei: None,
            imei_lock: None,
            runtime_data: None,
        }
    }
}
