/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EndpointQuota {
    #[serde(rename = "last_volume_added", skip_serializing_if = "Option::is_none")]
    pub last_volume_added: Option<f32>,
    #[serde(
        rename = "last_status_change_date",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_status_change_date: Option<String>,
    #[serde(rename = "auto_refill", skip_serializing_if = "Option::is_none")]
    pub auto_refill: Option<i32>,
    #[serde(rename = "threshold_volume", skip_serializing_if = "Option::is_none")]
    pub threshold_volume: Option<f32>,
    #[serde(
        rename = "threshold_percentage",
        skip_serializing_if = "Option::is_none"
    )]
    pub threshold_percentage: Option<f32>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::QuotaStatus>,
    #[serde(rename = "volume")]
    pub volume: f32,
    #[serde(rename = "expiry_date")]
    pub expiry_date: String,
    #[serde(rename = "action_on_exhaustion")]
    pub action_on_exhaustion: Box<crate::models::ActionOnExhaustion>,
    #[serde(rename = "peak_throughput", skip_serializing_if = "Option::is_none")]
    pub peak_throughput: Option<i32>,
}

impl EndpointQuota {
    pub fn new(
        status: crate::models::QuotaStatus,
        volume: f32,
        expiry_date: String,
        action_on_exhaustion: crate::models::ActionOnExhaustion,
    ) -> EndpointQuota {
        EndpointQuota {
            last_volume_added: None,
            last_status_change_date: None,
            auto_refill: None,
            threshold_volume: None,
            threshold_percentage: None,
            status: Box::new(status),
            volume,
            expiry_date,
            action_on_exhaustion: Box::new(action_on_exhaustion),
            peak_throughput: None,
        }
    }
}
