/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    #[serde(rename = "status")]
    pub status: crate::models::ApiV1EndpointStatus,
    #[serde(rename = "service_profile")]
    pub service_profile: crate::models::ApiV1EndpointStatus,
    #[serde(rename = "tariff_profile")]
    pub tariff_profile: crate::models::ApiV1EndpointStatus,
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "ip_address_space", skip_serializing_if = "Option::is_none")]
    pub ip_address_space: Option<crate::models::ApiV1EndpointStatus>,
    #[serde(rename = "sim", skip_serializing_if = "Option::is_none")]
    pub sim: Option<crate::models::ApiV1EndpointSim>,
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(rename = "imei_lock", skip_serializing_if = "Option::is_none")]
    pub imei_lock: Option<bool>,
}

impl Endpoint {
    pub fn new(name: String, status: crate::models::ApiV1EndpointStatus, service_profile: crate::models::ApiV1EndpointStatus, tariff_profile: crate::models::ApiV1EndpointStatus) -> Endpoint {
        Endpoint {
            name,
            tags: None,
            status,
            service_profile,
            tariff_profile,
            ip_address: None,
            ip_address_space: None,
            sim: None,
            imei: None,
            imei_lock: None,
        }
    }
}


