/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "alert", skip_serializing_if = "Option::is_none")]
    pub alert: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<crate::models::ApiV1EventEventType>,
    #[serde(rename = "event_source", skip_serializing_if = "Option::is_none")]
    pub event_source: Option<crate::models::ApiV1EventEventSource>,
    #[serde(rename = "event_severity", skip_serializing_if = "Option::is_none")]
    pub event_severity: Option<crate::models::ApiV1EventEventSeverity>,
    #[serde(rename = "organisation", skip_serializing_if = "Option::is_none")]
    pub organisation: Option<crate::models::ApiV1EventOrganisation>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<crate::models::ApiV1EventUser>,
}

impl Event {
    pub fn new() -> Event {
        Event {
            id: None,
            alert: None,
            description: None,
            timestamp: None,
            event_type: None,
            event_source: None,
            event_severity: None,
            organisation: None,
            user: None,
        }
    }
}


