/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDataStreamerByIdV2200ResponseAllOfStatus {
    /// Status identifier
    #[serde(rename = "id")]
    pub id: f32,
    /// Status description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl GetDataStreamerByIdV2200ResponseAllOfStatus {
    pub fn new(id: f32) -> GetDataStreamerByIdV2200ResponseAllOfStatus {
        GetDataStreamerByIdV2200ResponseAllOfStatus {
            id,
            description: None,
        }
    }
}
