/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetMonthlyOrganisationStatsResponseSim : Amount of SIMs per SIM status where the selected organisation is either the customer organisation or the issuer organisation

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMonthlyOrganisationStatsResponseSim {
    #[serde(rename = "issued", skip_serializing_if = "Option::is_none")]
    pub issued: Option<f32>,
    #[serde(rename = "factory_mode", skip_serializing_if = "Option::is_none")]
    pub factory_mode: Option<f32>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<f32>,
    #[serde(rename = "suspended", skip_serializing_if = "Option::is_none")]
    pub suspended: Option<f32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
}

impl GetMonthlyOrganisationStatsResponseSim {
    /// Amount of SIMs per SIM status where the selected organisation is either the customer organisation or the issuer organisation
    pub fn new() -> GetMonthlyOrganisationStatsResponseSim {
        GetMonthlyOrganisationStatsResponseSim {
            issued: None,
            factory_mode: None,
            active: None,
            suspended: None,
            total: None,
        }
    }
}
