/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHourlyOrganisationStatsResponseData {
    /// Downloaded data - Array index `0`: Time as `HH:mm` string, index `1`: consumed volume
    #[serde(rename = "rx", skip_serializing_if = "Option::is_none")]
    pub rx: Option<Vec<String>>,
    /// Uploaded data - Array index `0`: Time as `HH:mm` string, index `1`: consumed volume
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Vec<String>>,
}

impl GetHourlyOrganisationStatsResponseData {
    pub fn new() -> GetHourlyOrganisationStatsResponseData {
        GetHourlyOrganisationStatsResponseData { rx: None, tx: None }
    }
}
