/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMonthlyOrganisationStatsResponse {
    #[serde(rename = "current_month", skip_serializing_if = "Option::is_none")]
    pub current_month: Option<Box<crate::models::OrganisationTrafficStatisticsMonthObject>>,
    #[serde(rename = "last_month", skip_serializing_if = "Option::is_none")]
    pub last_month: Option<Box<crate::models::OrganisationTrafficStatisticsMonthObject>>,
    #[serde(rename = "sim", skip_serializing_if = "Option::is_none")]
    pub sim: Option<Box<crate::models::GetMonthlyOrganisationStatsResponseSim>>,
    /// Amount of service profiles
    #[serde(rename = "service_profiles", skip_serializing_if = "Option::is_none")]
    pub service_profiles: Option<f32>,
    /// Amount of service profiles
    #[serde(rename = "tariff_profiles", skip_serializing_if = "Option::is_none")]
    pub tariff_profiles: Option<f32>,
    /// Amount of users
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<f32>,
    /// Amount of active SIMs that will be charged within the current month. This field is omitted if there are no chargeable SIMs.
    #[serde(
        rename = "active_chargeable_sims",
        skip_serializing_if = "Option::is_none"
    )]
    pub active_chargeable_sims: Option<f32>,
    /// Total of SIM hosting fees for all `active_chargeable_sims`. This field is omitted if there are no chargeable SIMs.
    #[serde(rename = "hosting_fees", skip_serializing_if = "Option::is_none")]
    pub hosting_fees: Option<f32>,
    #[serde(rename = "inclusive_volume", skip_serializing_if = "Option::is_none")]
    pub inclusive_volume:
        Option<Box<crate::models::GetMonthlyOrganisationStatsResponseInclusiveVolume>>,
    #[serde(rename = "prepaid_balance", skip_serializing_if = "Option::is_none")]
    pub prepaid_balance:
        Option<Box<crate::models::GetMonthlyOrganisationStatsResponsePrepaidBalance>>,
}

impl GetMonthlyOrganisationStatsResponse {
    pub fn new() -> GetMonthlyOrganisationStatsResponse {
        GetMonthlyOrganisationStatsResponse {
            current_month: None,
            last_month: None,
            sim: None,
            service_profiles: None,
            tariff_profiles: None,
            users: None,
            active_chargeable_sims: None,
            hosting_fees: None,
            inclusive_volume: None,
            prepaid_balance: None,
        }
    }
}
