/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHourlyOrganisationStatsResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::GetHourlyOrganisationStatsResponseData>>,
    #[serde(rename = "sms", skip_serializing_if = "Option::is_none")]
    pub sms: Option<Box<crate::models::GetHourlyOrganisationStatsResponseSms>>,
}

impl GetHourlyOrganisationStatsResponse {
    pub fn new() -> GetHourlyOrganisationStatsResponse {
        GetHourlyOrganisationStatsResponse {
            data: None,
            sms: None,
        }
    }
}
