/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCloudConnectAttachmentByIdResponseInnerAllOf {
    #[serde(rename = "tunnel_information", skip_serializing_if = "Option::is_none")]
    pub tunnel_information: Option<
        Box<crate::models::GetCloudConnectAttachmentByIdResponseInnerAllOfTunnelInformation>,
    >,
}

impl GetCloudConnectAttachmentByIdResponseInnerAllOf {
    pub fn new() -> GetCloudConnectAttachmentByIdResponseInnerAllOf {
        GetCloudConnectAttachmentByIdResponseInnerAllOf {
            tunnel_information: None,
        }
    }
}
