/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetApiCallbackSecret200ResponseInner {
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<String>,
    #[serde(rename = "purpose", skip_serializing_if = "Option::is_none")]
    pub purpose: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl GetApiCallbackSecret200ResponseInner {
    pub fn new() -> GetApiCallbackSecret200ResponseInner {
        GetApiCallbackSecret200ResponseInner {
            organisation_id: None,
            purpose: None,
            id: None,
        }
    }
}
