/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHourlyOrganisationStatsResponseSms {
    /// SMS MO - Array index `0`: Time as `HH:mm` string, index `1`: consumed volume
    #[serde(rename = "rx", skip_serializing_if = "Option::is_none")]
    pub rx: Option<Vec<String>>,
    /// SMS MT - Array index `0`: Time as `HH:mm` string, index `1`: consumed volume
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<Vec<String>>,
}

impl GetHourlyOrganisationStatsResponseSms {
    pub fn new() -> GetHourlyOrganisationStatsResponseSms {
        GetHourlyOrganisationStatsResponseSms { rx: None, tx: None }
    }
}
