/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse404 {
    #[serde(rename = "error_code", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<f32>,
    #[serde(rename = "error_token", skip_serializing_if = "Option::is_none")]
    pub error_token: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl InlineResponse404 {
    pub fn new() -> InlineResponse404 {
        InlineResponse404 {
            error_code: None,
            error_token: None,
            message: None,
        }
    }
}


