/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2003 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<String>,
    #[serde(rename = "secondary", skip_serializing_if = "Option::is_none")]
    pub secondary: Option<String>,
    #[serde(rename = "ip_address_version", skip_serializing_if = "Option::is_none")]
    pub ip_address_version: Option<i32>,
}

impl InlineResponse2003 {
    pub fn new() -> InlineResponse2003 {
        InlineResponse2003 {
            id: None,
            primary: None,
            secondary: None,
            ip_address_version: None,
        }
    }
}


