/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListofTariffProfilesresponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "used_count", skip_serializing_if = "Option::is_none")]
    pub used_count: Option<i32>,
    #[serde(rename = "tariff", skip_serializing_if = "Option::is_none")]
    pub tariff: Option<serde_json::Value>,
}

impl ListofTariffProfilesresponse {
    pub fn new() -> ListofTariffProfilesresponse {
        ListofTariffProfilesresponse {
            id: None,
            name: None,
            description: None,
            used_count: None,
            tariff: None,
        }
    }
}


