/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

/// ListDataStreamerV2s200ResponseDestinationCredentialsOneOf : Credential fields for Amazon Kinesis Data Streams

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListDataStreamerV2s200ResponseDestinationCredentialsOneOf {
    /// AWS Region of your Kinesis Data Stream
    #[serde(rename = "region")]
    pub region: String,
    /// Name of your Kinesis Data Stream
    #[serde(rename = "stream_name")]
    pub stream_name: String,
    /// Role ARN of IAM role with write permission for your Kinesis Stream
    #[serde(rename = "role_arn")]
    pub role_arn: String,
}

impl ListDataStreamerV2s200ResponseDestinationCredentialsOneOf {
    /// Credential fields for Amazon Kinesis Data Streams
    pub fn new(
        region: String,
        stream_name: String,
        role_arn: String,
    ) -> ListDataStreamerV2s200ResponseDestinationCredentialsOneOf {
        ListDataStreamerV2s200ResponseDestinationCredentialsOneOf {
            region,
            stream_name,
            role_arn,
        }
    }
}
