/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

/// ListDataStreamerV2s200ResponseDestinationCredentialsOneOf5 : Credential fields for Microsoft Azure EventHub

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListDataStreamerV2s200ResponseDestinationCredentialsOneOf5 {
    /// Connection string with Access Key to your Event Hub.
    #[serde(rename = "connection_string")]
    pub connection_string: String,
}

impl ListDataStreamerV2s200ResponseDestinationCredentialsOneOf5 {
    /// Credential fields for Microsoft Azure EventHub
    pub fn new(
        connection_string: String,
    ) -> ListDataStreamerV2s200ResponseDestinationCredentialsOneOf5 {
        ListDataStreamerV2s200ResponseDestinationCredentialsOneOf5 { connection_string }
    }
}
