/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCloudConnectCustomResponseInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "breakout_type_id", skip_serializing_if = "Option::is_none")]
    pub breakout_type_id: Option<i32>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Box<crate::models::ListCloudConnectCustomResponseInnerAllOfCurrency>>,
}

impl ListCloudConnectCustomResponseInner {
    pub fn new() -> ListCloudConnectCustomResponseInner {
        ListCloudConnectCustomResponseInner {
            id: None,
            breakout_type_id: None,
            amount: None,
            currency: None,
        }
    }
}
