/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListDataStreamerV2s200ResponseFiltersInner {
    /// Field to filter on
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    /// Values to filter on
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Vec<String>>,
}

impl ListDataStreamerV2s200ResponseFiltersInner {
    pub fn new() -> ListDataStreamerV2s200ResponseFiltersInner {
        ListDataStreamerV2s200ResponseFiltersInner {
            field: None,
            value: None,
        }
    }
}
