/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanServiceLevel : The default service level of a tariff plan. Possible values can be fetched with GET `/api/v1/service_level`.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanServiceLevel {
    #[serde(rename = "id")]
    pub id: f32,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanServiceLevel {
    /// The default service level of a tariff plan. Possible values can be fetched with GET `/api/v1/service_level`.
    pub fn new(id: f32) -> OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanServiceLevel {
        OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanServiceLevel { id, name: None }
    }
}
