/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanPrice {
    #[serde(rename = "sim_activated_rate", skip_serializing_if = "Option::is_none")]
    pub sim_activated_rate: Option<Vec<crate::models::OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanPriceSimActivatedRateInner>>,
}

impl OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanPrice {
    pub fn new() -> OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanPrice {
        OrganisationTariffPlanByOrgIdGet200ResponseInnerTariffPlanPrice {
            sim_activated_rate: None,
        }
    }
}
