/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganisationTrafficStatisticsObjectTrafficType {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
}

impl OrganisationTrafficStatisticsObjectTrafficType {
    pub fn new() -> OrganisationTrafficStatisticsObjectTrafficType {
        OrganisationTrafficStatisticsObjectTrafficType {
            description: None,
            unit: None,
            id: None,
        }
    }
}
