/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrganisationTariffPlanByOrgIdGet200ResponseInnerServiceLevel : Custom service level for the organisation. If set to null, the default service level from the tariff plan will be applied.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganisationTariffPlanByOrgIdGet200ResponseInnerServiceLevel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl OrganisationTariffPlanByOrgIdGet200ResponseInnerServiceLevel {
    /// Custom service level for the organisation. If set to null, the default service level from the tariff plan will be applied.
    pub fn new() -> OrganisationTariffPlanByOrgIdGet200ResponseInnerServiceLevel {
        OrganisationTariffPlanByOrgIdGet200ResponseInnerServiceLevel {
            id: None,
            name: None,
        }
    }
}
