/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QuotaStatus {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Description>,
    #[serde(rename = "id")]
    pub id: Id,
}

impl QuotaStatus {
    pub fn new(id: Id) -> QuotaStatus {
        QuotaStatus {
            description: None,
            id,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Description {
    #[serde(rename = "EXHAUSTED")]
    Exhausted,
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl Default for Description {
    fn default() -> Description {
        Self::Exhausted
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Id {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for Id {
    fn default() -> Id {
        Self::Variant1
    }
}
