/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReSendActivationMailrequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "g-recaptcha-response")]
    pub g_recaptcha_response: String,
}

impl ReSendActivationMailrequest {
    pub fn new(username: String, g_recaptcha_response: String) -> ReSendActivationMailrequest {
        ReSendActivationMailrequest {
            username,
            g_recaptcha_response,
        }
    }
}
