/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseOfActivatableSimBatch {
    #[serde(
        rename = "sim_batch_status_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub sim_batch_status_id: Option<String>,
    #[serde(rename = "bsn", skip_serializing_if = "Option::is_none")]
    pub bsn: Option<String>,
    #[serde(rename = "bic", skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    #[serde(rename = "sim_model_id", skip_serializing_if = "Option::is_none")]
    pub sim_model_id: Option<String>,
    #[serde(rename = "issuer_org_id", skip_serializing_if = "Option::is_none")]
    pub issuer_org_id: Option<String>,
    #[serde(rename = "customer_org_id", skip_serializing_if = "Option::is_none")]
    pub customer_org_id: Option<i32>,
    #[serde(rename = "reseller_org_id", skip_serializing_if = "Option::is_none")]
    pub reseller_org_id: Option<i32>,
    #[serde(rename = "activated", skip_serializing_if = "Option::is_none")]
    pub activated: Option<String>,
    #[serde(rename = "logistic_center_id", skip_serializing_if = "Option::is_none")]
    pub logistic_center_id: Option<String>,
    #[serde(rename = "article_id", skip_serializing_if = "Option::is_none")]
    pub article_id: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::Status>>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<crate::models::SimModel>>,
}

impl ResponseOfActivatableSimBatch {
    pub fn new() -> ResponseOfActivatableSimBatch {
        ResponseOfActivatableSimBatch {
            sim_batch_status_id: None,
            bsn: None,
            bic: None,
            quantity: None,
            sim_model_id: None,
            issuer_org_id: None,
            customer_org_id: None,
            reseller_org_id: None,
            activated: None,
            logistic_center_id: None,
            article_id: None,
            id: None,
            status: None,
            model: None,
        }
    }
}
