/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAvailableEsmeInterfaceTypesresponse {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "description")]
    pub description: String,
}

impl RetrieveAvailableEsmeInterfaceTypesresponse {
    pub fn new(id: i32, description: String) -> RetrieveAvailableEsmeInterfaceTypesresponse {
        RetrieveAvailableEsmeInterfaceTypesresponse { id, description }
    }
}
