/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveEndpointStatisticsresponse {
    #[serde(rename = "last_month", skip_serializing_if = "Option::is_none")]
    pub last_month: Option<serde_json::Value>,
    #[serde(rename = "current_month", skip_serializing_if = "Option::is_none")]
    pub current_month: Option<serde_json::Value>,
    #[serde(rename = "last_hour", skip_serializing_if = "Option::is_none")]
    pub last_hour: Option<serde_json::Value>,
}

impl RetrieveEndpointStatisticsresponse {
    pub fn new() -> RetrieveEndpointStatisticsresponse {
        RetrieveEndpointStatisticsresponse {
            last_month: None,
            current_month: None,
            last_hour: None,
        }
    }
}
