/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveCoverageresponse {
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<serde_json::Value>,
    #[serde(rename = "redundancy_count", skip_serializing_if = "Option::is_none")]
    pub redundancy_count: Option<i32>,
}

impl RetrieveCoverageresponse {
    pub fn new() -> RetrieveCoverageresponse {
        RetrieveCoverageresponse {
            country: None,
            redundancy_count: None,
        }
    }
}
