/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveEndpointConnectivityStatusresponse {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<serde_json::Value>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<serde_json::Value>,
    #[serde(rename = "pdp_context", skip_serializing_if = "Option::is_none")]
    pub pdp_context: Option<serde_json::Value>,
    ///
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<String>>,
}

impl RetrieveEndpointConnectivityStatusresponse {
    pub fn new() -> RetrieveEndpointConnectivityStatusresponse {
        RetrieveEndpointConnectivityStatusresponse {
            status: None,
            location: None,
            pdp_context: None,
            services: None,
        }
    }
}
