/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveSingleEndpointresponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<serde_json::Value>,
    #[serde(rename = "service_profile", skip_serializing_if = "Option::is_none")]
    pub service_profile: Option<serde_json::Value>,
    #[serde(rename = "tariff_profile", skip_serializing_if = "Option::is_none")]
    pub tariff_profile: Option<serde_json::Value>,
    #[serde(rename = "sim", skip_serializing_if = "Option::is_none")]
    pub sim: Option<serde_json::Value>,
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(rename = "imei_lock", skip_serializing_if = "Option::is_none")]
    pub imei_lock: Option<bool>,
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "ip_address_space", skip_serializing_if = "Option::is_none")]
    pub ip_address_space: Option<serde_json::Value>,
    #[serde(rename = "runtime_data", skip_serializing_if = "Option::is_none")]
    pub runtime_data: Option<serde_json::Value>,
}

impl RetrieveSingleEndpointresponse {
    pub fn new() -> RetrieveSingleEndpointresponse {
        RetrieveSingleEndpointresponse {
            id: None,
            name: None,
            tags: None,
            created: None,
            last_updated: None,
            status: None,
            service_profile: None,
            tariff_profile: None,
            sim: None,
            imei: None,
            imei_lock: None,
            ip_address: None,
            ip_address_space: None,
            runtime_data: None,
        }
    }
}


