/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAvailableDataThrottlesresponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "octets", skip_serializing_if = "Option::is_none")]
    pub octets: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl RetrieveAvailableDataThrottlesresponse {
    pub fn new() -> RetrieveAvailableDataThrottlesresponse {
        RetrieveAvailableDataThrottlesresponse {
            id: None,
            octets: None,
            description: None,
        }
    }
}
