/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveAvailableBreakoutRegionsresponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

impl RetrieveAvailableBreakoutRegionsresponse {
    pub fn new() -> RetrieveAvailableBreakoutRegionsresponse {
        RetrieveAvailableBreakoutRegionsresponse {
            id: None,
            name: None,
            ip_address: None,
        }
    }
}
