/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceTrafficLimitInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<i32>,
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<Box<crate::models::ServiceTrafficLimitInnerPeriod>>,
}

impl ServiceTrafficLimitInner {
    pub fn new() -> ServiceTrafficLimitInner {
        ServiceTrafficLimitInner {
            id: None,
            volume: None,
            period: None,
        }
    }
}
