/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.2.26
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleSimResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "iccid", skip_serializing_if = "Option::is_none")]
    pub iccid: Option<String>,
    #[serde(rename = "production_date", skip_serializing_if = "Option::is_none")]
    pub production_date: Option<String>,
    #[serde(rename = "activation_date", skip_serializing_if = "Option::is_none")]
    pub activation_date: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<serde_json::Value>,
    #[serde(rename = "customer_org", skip_serializing_if = "Option::is_none")]
    pub customer_org: Option<serde_json::Value>,
    #[serde(rename = "issuer_org", skip_serializing_if = "Option::is_none")]
    pub issuer_org: Option<serde_json::Value>,
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<serde_json::Value>,
    #[serde(rename = "imsi", skip_serializing_if = "Option::is_none")]
    pub imsi: Option<String>,
    #[serde(rename = "msisdn", skip_serializing_if = "Option::is_none")]
    pub msisdn: Option<String>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<serde_json::Value>,
    #[serde(rename = "reseller_org", skip_serializing_if = "Option::is_none")]
    pub reseller_org: Option<serde_json::Value>,
}

impl SingleSimResource {
    pub fn new() -> SingleSimResource {
        SingleSimResource {
            id: None,
            iccid: None,
            production_date: None,
            activation_date: None,
            status: None,
            customer_org: None,
            issuer_org: None,
            endpoint: None,
            imsi: None,
            msisdn: None,
            model: None,
            reseller_org: None,
        }
    }
}


