/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StartingaUssdDialogrequest {
    #[serde(rename = "ussd-begin")]
    pub ussd_begin: serde_json::Value,
}

impl StartingaUssdDialogrequest {
    pub fn new(ussd_begin: serde_json::Value) -> StartingaUssdDialogrequest {
        StartingaUssdDialogrequest { ussd_begin }
    }
}
