/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitMtSmSrequest {
    #[serde(rename = "source_address")]
    pub source_address: String,
    #[serde(rename = "payload")]
    pub payload: String,
}

impl SubmitMtSmSrequest {
    pub fn new(source_address: String, payload: String) -> SubmitMtSmSrequest {
        SubmitMtSmSrequest {
            source_address,
            payload,
        }
    }
}
