/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SuccessfulBatchActivation {
    #[serde(rename = "sim", skip_serializing_if = "Option::is_none")]
    pub sim: Option<Vec<crate::models::SimEntry>>,
}

impl SuccessfulBatchActivation {
    pub fn new() -> SuccessfulBatchActivation {
        SuccessfulBatchActivation { sim: None }
    }
}
