/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TariffProfile1Tariff {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "tariff_status_id", skip_serializing_if = "Option::is_none")]
    pub tariff_status_id: Option<String>,
    #[serde(rename = "currency_id", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<String>,
    #[serde(
        rename = "default_sms_mt_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_sms_mt_rate: Option<f32>,
    #[serde(
        rename = "default_sms_mo_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_sms_mo_rate: Option<f32>,
    #[serde(rename = "sim_issued_rate", skip_serializing_if = "Option::is_none")]
    pub sim_issued_rate: Option<f32>,
    #[serde(rename = "sim_activated_rate", skip_serializing_if = "Option::is_none")]
    pub sim_activated_rate: Option<f32>,
    #[serde(rename = "sim_suspended_rate", skip_serializing_if = "Option::is_none")]
    pub sim_suspended_rate: Option<f32>,
    #[serde(
        rename = "sim_activation_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub sim_activation_rate: Option<f32>,
    #[serde(
        rename = "sim_reactivation_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub sim_reactivation_rate: Option<f32>,
    #[serde(
        rename = "sim_suspension_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub sim_suspension_rate: Option<f32>,
    #[serde(
        rename = "sim_termination_rate",
        skip_serializing_if = "Option::is_none"
    )]
    pub sim_termination_rate: Option<f32>,
    #[serde(rename = "data_throttle_id", skip_serializing_if = "Option::is_none")]
    pub data_throttle_id: Option<String>,
    #[serde(rename = "data_blocksize_id", skip_serializing_if = "Option::is_none")]
    pub data_blocksize_id: Option<String>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<String>,
    #[serde(rename = "tariff_category_id", skip_serializing_if = "Option::is_none")]
    pub tariff_category_id: Option<String>,
    #[serde(rename = "visibility_id", skip_serializing_if = "Option::is_none")]
    pub visibility_id: Option<String>,
    #[serde(
        rename = "tariff_currency_category_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub tariff_currency_category_id: Option<String>,
    #[serde(rename = "used_count", skip_serializing_if = "Option::is_none")]
    pub used_count: Option<String>,
    #[serde(rename = "assigned_count", skip_serializing_if = "Option::is_none")]
    pub assigned_count: Option<String>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Box<crate::models::TariffProfile1TariffCurrency>>,
}

impl TariffProfile1Tariff {
    pub fn new() -> TariffProfile1Tariff {
        TariffProfile1Tariff {
            id: None,
            organisation_id: None,
            name: None,
            description: None,
            created: None,
            tariff_status_id: None,
            currency_id: None,
            default_sms_mt_rate: None,
            default_sms_mo_rate: None,
            sim_issued_rate: None,
            sim_activated_rate: None,
            sim_suspended_rate: None,
            sim_activation_rate: None,
            sim_reactivation_rate: None,
            sim_suspension_rate: None,
            sim_termination_rate: None,
            data_throttle_id: None,
            data_blocksize_id: None,
            public: None,
            tariff_category_id: None,
            visibility_id: None,
            tariff_currency_category_id: None,
            used_count: None,
            assigned_count: None,
            currency: None,
        }
    }
}
