/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateEndpoint {
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::Status>>,
    #[serde(rename = "service_profile", skip_serializing_if = "Option::is_none")]
    pub service_profile: Option<Box<crate::models::ServiceProfile>>,
    #[serde(rename = "tariff_profile", skip_serializing_if = "Option::is_none")]
    pub tariff_profile: Option<Box<crate::models::TariffProfile>>,
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "ip_address_space", skip_serializing_if = "Option::is_none")]
    pub ip_address_space: Option<Box<crate::models::HasId>>,
    #[serde(rename = "sim", skip_serializing_if = "Option::is_none")]
    pub sim: Option<Box<crate::models::HasId>>,
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    #[serde(rename = "imei_lock", skip_serializing_if = "Option::is_none")]
    pub imei_lock: Option<bool>,
}

impl UpdateEndpoint {
    pub fn new() -> UpdateEndpoint {
        UpdateEndpoint {
            tags: None,
            status: None,
            service_profile: None,
            tariff_profile: None,
            ip_address: None,
            ip_address_space: None,
            sim: None,
            imei: None,
            imei_lock: None,
        }
    }
}
