/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateSim {
    #[serde(rename = "issuer_org", skip_serializing_if = "Option::is_none")]
    pub issuer_org: Option<Box<crate::models::HasId>>,
    #[serde(rename = "reseller_org", skip_serializing_if = "Option::is_none")]
    pub reseller_org: Option<Box<crate::models::HasId>>,
    #[serde(rename = "customer_org", skip_serializing_if = "Option::is_none")]
    pub customer_org: Option<Box<crate::models::HasId>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::Status>>,
}

impl UpdateSim {
    pub fn new() -> UpdateSim {
        UpdateSim {
            issuer_org: None,
            reseller_org: None,
            customer_org: None,
            status: None,
        }
    }
}
