/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserByIdV2CreateSupportTokenRequest1 {
    #[serde(rename = "support_token", skip_serializing_if = "Option::is_none")]
    pub support_token: Option<String>,
}

impl UserByIdV2CreateSupportTokenRequest1 {
    pub fn new() -> UserByIdV2CreateSupportTokenRequest1 {
        UserByIdV2CreateSupportTokenRequest1 {
            support_token: None,
        }
    }
}
