/*
 * EMnify Rest API
 *
 * Rest API resources of the EMnify System.
 *
 * The version of the OpenAPI document: 1.3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserByIdV2CreateSupportTokenRequest {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
}

impl UserByIdV2CreateSupportTokenRequest {
    pub fn new() -> UserByIdV2CreateSupportTokenRequest {
        UserByIdV2CreateSupportTokenRequest { role: None }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for Role {
    fn default() -> Role {
        Self::Variant1
    }
}
